# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [8]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
# The underscores are needed to show the actual version as opposed to a file containging the version number
print(np.__version__)

# This can be used without enclosing it in print() 
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/tom/anaconda3/envs/intro-week/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/tom/anaconda3/envs/intro-week/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/tom/anaconda3/envs/intro-week/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/tom/anaconda3/envs/intro-week/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/tom/anaconda3/envs/intro-week/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/tom/anaconda3/envs/intro-week/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/tom/anaconda3/envs/intro-week/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/tom/anaconda3/envs/intro-week/inc

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
# Dimension ranks: 0 is scalar, 1 is vector, 2 is matrix, 3 is tensor

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
# np.size()
some_array = np.zeros(5)
np.size(some_array)

5

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# In general: help(<function name>)
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector = np.zeros(10)
# We start from the 0th index...
null_vector[4] = 1

print(np.size(null_vector))
print(null_vector)
print(null_vector[4])

10
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
1.0


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
# This function creates "A Range" of values, it does not "Arrange" values
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [21]:
reverse_me = np.arange(1,11,1)
print(reverse_me)
np.flip(reverse_me)

[ 1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
# Numbers to put in
row_one = [0,1,2]
row_two = [3,4,5]
row_three = [6,7,8]

np.matrix([row_one,row_two,row_three])

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [36]:
# Boolean Indexing

data = np.array([1,2,0,0,4,0])

# We will make a new array to store the location of non-zeros
non_zero_indices = np.where( data != 0)
print(non_zero_indices)

# This will give the values of those indices
#print(data[non_zero_indices])


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [39]:
# An identity matrix is a square matrix with 1s going diagonally through it, it's useful for computing the inverse of a matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [45]:
# Random values are helpful for testing random things
np.random.rand(3,3,3)

array([[[0.27356602, 0.84633337, 0.76010955],
        [0.93888617, 0.78693963, 0.47195343],
        [0.71384278, 0.30527739, 0.36614889]],

       [[0.88102294, 0.22969743, 0.93667815],
        [0.25993161, 0.7918816 , 0.77634111],
        [0.47491157, 0.39581926, 0.13112991]],

       [[0.31818629, 0.79829907, 0.6006846 ],
        [0.9518483 , 0.72743793, 0.59673972],
        [0.3503375 , 0.46035254, 0.35721637]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [51]:
ten_by_ten = np.random.rand(10,10)
#print(ten_by_ten)

# Numpy has sensible names for many functions
minimum = np.min(ten_by_ten)
maximum = np.max(ten_by_ten)

print(f"Min: {minimum} | Max: {maximum}")

Min: 0.002536644890521078 | Max: 0.9968565800512061


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [52]:
random_vector = np.random.rand(30)
#print(random_vector)

print(np.size(random_vector))

print(np.mean(random_vector))

30
0.5220037010633192


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [77]:
# For the smallest valid array (3x3) we can just change it manually
border_array = np.ones([3,3])
border_array[1,1] = 0

print(border_array)

print()
print("---------")
print("A bigger version:")

# But for anything larger we should probably construct the array with commands
scalable_version = np.zeros([10,10])
#print(scalable_version)
scalable_version[:,0] = 1
scalable_version[0,:] = 1
scalable_version[:,-1] = 1
scalable_version[-1,:] = 1
print(scalable_version)

# I tried to put the above all into one command, but couldn't figure out the syntax
# If you know it, let me know in the feedback please :-)
#scalable_version([:,0],[0,:].[:,-1],[-1,:]) = 1

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

---------
A bigger version:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [131]:
enclosed_array = np.ones([4,6])
print("Start:")
print(enclosed_array)
print()
print("=====")
print()

# To generate some 0s we need to know how many we need
# This will store the dimensions of the array to enclose
shape = np.shape(enclosed_array)

# This adds a column of zeros onto the end and start of our original array 
enclosed_array = np.column_stack((enclosed_array, np.zeros([shape[0]])))
enclosed_array = np.column_stack((np.zeros([shape[0]]) , enclosed_array))

# The shape has changed because we added 2 columns
shape = np.shape(enclosed_array)
# We just need to add a row of zeros at the start and end of the original array
top_and_bottom = np.zeros(shape[1])

# I used two different methods here just for fun, vstack just "stacks" rows together,
# Whereas insert allows you to choose exactly where to input the data
enclosed_array = np.vstack((enclosed_array, top_and_bottom))
enclosed_array = np.insert(enclosed_array, 0, 0, axis=0)

print("Finally:")
print(enclosed_array)


Start:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

=====

Finally:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [151]:
# So first, we are multiplying 0 by "nan" which is not a number, so this will result in "nan"
0 * np.nan
print(0 * np.nan) # nan

# Next we are seeing if nan is equal to itself, which I thought would be true BUT
# a nan is just a lack of data and by definition, nan != nan
np.nan == np.nan
print(np.nan == np.nan) # False

# This is attempting to compare positive infinity to not-a-number, resulting in false
np.inf > np.nan
print(np.inf > np.nan) # False

# Can we take away one nan from another? They aren't numbers so it just results in nan
np.nan - np.nan
print(np.nan - np.nan) # nan

# This one we can do, as we are seeing if a nan exists in a set containing a nan (which it does)
np.nan in set([np.nan])
print(np.nan in set([np.nan])) # True

# Finally some arithmetic, this is True in real life,
# HOWEVER: Due to how decimal numbers are handled by computers, comparing them is  generally unreliable.
0.3 == 3 * 0.1
print(0.3 == 3 * 0.1) # False


# These statements are independant of each other so the final result of these expressions is
# False
print("=====")
print(False)

nan
False
False
nan
True
False
=====
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(self)
 |  
 |  __le__

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)