72. How to swap two rows of an array? (★★★)

In [2]:
import numpy as np

row1 = [1,11,111,1111,11111]
row2 = [2,22,222,2222,22222]
row3 = [3,33,333,3333,33333]
row4 = [4,44,444,4444,44444]
row5 = [5,55,555,5555,55555]

swap_me = np.array([row1,row2,row3,row4,row5])
print(swap_me)

print()
print("=====")
print()

# This command does not actually require the ",:" term as it will default to it
swap_me[ [0,3] , :] = swap_me[ [3,0] , :]
print(swap_me)

[[    1    11   111  1111 11111]
 [    2    22   222  2222 22222]
 [    3    33   333  3333 33333]
 [    4    44   444  4444 44444]
 [    5    55   555  5555 55555]]

=====

[[    4    44   444  4444 44444]
 [    2    22   222  2222 22222]
 [    3    33   333  3333 33333]
 [    1    11   111  1111 11111]
 [    5    55   555  5555 55555]]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [36]:
# I'm not certain I fully understand the question,
# but from what I can gather on discord and the hint,
# We need to calculate an average for each size of the array.

# So I will use an array of numbers 1 to 100,
# Calculate the mean from the cumulative total.
# This will be so by the Nth value, we have the mean of the first 10 values.

an_array = np.indices([100]) + 1
my_indices = np.indices([100]) + 1

cum_sum_of_array = np.array(np.cumsum(an_array))

#print(my_indices)

#print(cum_sum_of_array)

expanding_window_average = np.divide(cum_sum_of_array,my_indices)
print(expanding_window_average)

[[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
   8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
  15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5
  22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5
  29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5
  36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5
  43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5
  50.  50.5]]
