## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np
import pandas as pd

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [ ]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A):
    # I'm pressed for time, but https://www.mathsisfun.com/algebra/matrix-inverse.html and https://www.mathsisfun.com/algebra/matrix-determinant.html
    # Explain the concept well
    return numpy.linalg.inv(A)

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [33]:
# Just answer using code --> easy stuff!
A = np.matrix([[3,-1.3,7],[0.6,4,0],[4,0,-8],[-3,8.6,0.006]])
B = np.matrix([[3,2,9],[-5.76,-2,0],[45,1.3,0],[0,9,0]])
C = np.matrix([[0,0,-7.7],[1009,5,0],[-66.7849,4,0],[90,-0.07,0]])

temp = np.add(A,B)
#print(A+B-C)
D = (A+B-C)
print(D)

print("=====")
i = 2
j = 3
# Minusing one because 0-index
print(str(D[i]))


# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

[[ 6.000000e+00  7.000000e-01  2.370000e+01]
 [-1.014160e+03 -3.000000e+00  0.000000e+00]
 [ 1.157849e+02 -2.700000e+00 -8.000000e+00]
 [-9.300000e+01  1.767000e+01  6.000000e-03]]
=====
[[115.7849  -2.7     -8.    ]]


![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [ ]:
"""
Minimum of rows of A and B
Minimum of columns of A and B
"""